### ISSUE TITLE
gem included parlour.rbi file problems

### ISSUE THREAD

**Issue by will** [AaronC81/parlour#101] opened 2020-08-18 14:02 UTC
We've been having some problems with the rbi for parlour itself included in the gem.

**github actions**

On github actions, sorbet complains about two constants needing `T.let`, even though on my mac and my colleague's linux `srb tc` is fine. 

I have `/vendor` ignored in `sorbet/config`. I tried ignoring `vendor`, `/vendor/` and even the full path here:

```
Run bundle exec srb tc --ignore=/home/runner/work/myproj/vendor
/home/runner/work/myproj/vendor/bundle/ruby/2.6.0/gems/parlour-4.0.1/rbi/parlour.rbi:723: Constants must have type annotations with `T.let` when specifying `# typed: strict` https://srb.help/5028
     723 |      PREFIXES = {
     724 |        normal: '',
     725 |        splat: '*',
     726 |        double_splat: '**',
     727 |        block: '&'
     728 |      }.freeze

/home/runner/work/myproj/vendor/bundle/ruby/2.6.0/gems/parlour-4.0.1/rbi/parlour.rbi:828: Constants must have type annotations with `T.let` when specifying `# typed: strict` https://srb.help/5028
     828 |      EXTRA_PROPERTIES = %i{
     829 |        optional enum dont_store foreign default factory immutable array override redaction
     830 |      }
Errors: 2
##[error]Process completed with exit code 1.

```

but no matter what sorbet would blow up at this. Right now I'm `rm`ing that rbi file in a new step before running sorbet, but that will break when the version number breaks. 

**mac vs linux?**

A second problem, on my mac sorbet seems to find the parlour included rbi for itself, and sorbet will get angry if the rbi for it in the project's /sorbet directory is different. On colleague's linux computer sorbet seems to ignore the version included in the gem. This would cause problems if he used sorbet to regenerate rbi files for gems and not copy over the one from inside parlour. 

I've recently switched to using tapioca instead to generate gem rbis, so maybe this isn't a problem anymore.

**misc**

I think parlour is probably the only gem that is including it's own rbi files. It feels like I'm missing something, so I worry that things will get worse if other gems start doing this too. IIf you have any experience dealing with gem-included rbi files correctly, please let me know.

**Comment by AaronC81** [comment] 2020-08-19 20:56
Hmm... the difference in behavior between platforms here is really odd. Thanks for reporting it, I'll look into this over the weekend!

As far as I understand, bundling an RBI with a gem is a [recommended way](https://sorbet.org/docs/rbi#rbis-within-gems) of making its types accessible to Sorbet in other projects...

>We expect that as adoption grows, gems will include their external interfaces RBI files in an rbi/ directory. When they do this, Sorbet will automatically include those definitions when typechecking a project. In the future, we anticipate this to be the preferred way to include RBI files into a project.

...though I'm not sure if this differs if the gem is also using inline types, like Parlour is.

**Comment by connorshea** [comment] 2020-08-19 20:57
@AaronC81 check the sorbet issue tracker, I'm pretty sure this is busted because sorbet doesn't handle multiple directories correctly in some cases.

**Comment by AaronC81** [comment] 2020-08-25 21:52
I set up a simple GitHub repo with Actions enabled, and I'm afraid I couldn't reproduce the constant type errors. 

What version of Sorbet are you using @will? I've tried 0.5.5669 and 0.5.5878 which both seemed fine.

**Comment by reidab** [comment] 2021-02-17 00:23
It seems like this could be related to this issue https://github.com/sorbet/sorbet/issues/3403, which I was able to repro using parlour as an example: https://github.com/sorbet/sorbet/issues/3403#issuecomment-779589132

When I run `srb rbi gems` on my local machine, sorbet is rewriting the `rbi/parlour.rbi` inside the installed copy of the gem, changing its sigil to `typed: ignore`. 

If I then run `bundle pristine parlour` or run a type check in an environment like GitHub actions with a clean install of the gem, `srb tc` fails.

**Comment by connorshea** [comment] 2021-02-28 02:13
I just ran into the exact situation @reidab described after running `bundle pristine` due to an issue I was debugging in something else.

I don't use `srb rbi gems` anymore (I use Tapioca), but even after I tried running it, the Sorbet LSP is still flipping out about the second directory existing >.>

I tried to delete the directory entirely but it seems to have it cached and errors about its lack of existence.

I think we should maybe just remove the RBI file from the gem for now?

**Comment by AaronC81** [comment] 2021-02-28 12:28
Adding the RBI to sorbet-typed is a really good idea, since that still keeps it available if you'd like it, but you can presumably opt not to download it if you're having problems.

I'll look at putting out a new release with the RBI not bundled, and submitted to sorbet-typed instead.

Thank you all for reporting this in such good detail - hopefully this will sort it out :)

**Comment by AaronC81** [comment] 2021-03-01 23:58
Parlour 6.0.0 has been released, which doesn't bundle an RBI, so should hopefully fix this!

I'll close this issue for now, but please leave a comment if you're still hitting any issues and I'll reopen.

**Closed by AaronC81** 2021-03-01 23:58 UTC
Labels: bug
